version: '3.9'
services:
  sms:
    build: ./
    container_name: backend
    depends_on:
      - mysql
    ports:
      - 8088:8088
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://mysql:3306/schoolmanagement?useUnicode=yes&characterEncoding=UTF-8",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "root",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '8889:3306'
    expose:
      - '3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    command: mysqld --character-set-server=utf8 --collation-server=utf8_turkish_ci
volumes:
  mysql-volume:
  mycustom.cnf:
 