version: '3.3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '8889:3306'
    expose:
      - '3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    command: mysqld --character-set-server=utf8 --collation-server=utf8_turkish_ci  
volumes:
  mysql-volume:
  mycustom.cnf:
 